[workspace] 
members = [
    "crates/actors",
    "crates/cli", 
    "crates/clients", 
    "crates/compute", 
    "crates/contract", 
    "crates/messages",
    "crates/node", 
    "crates/rpc", 
    "crates/types", 
    "crates/wallet"
] 
