version: "3.8"

services:
  ipfs:
    build:
      context: ./infra/ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data/ipfs
    restart: unless-stopped
    networks:
      - lasr

  foundry:
    build:
      context: ./infra/foundry
    ports:
      - "8545:8545"
    restart: unless-stopped
    networks:
      - lasr

  lasr:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - BLOCKS_PROCESSED_PATH="/data/blocks_processed.dat"
    volumes:
      - lasr_data:/data
    networks:
      - lasr

networks:
  lasr:

volumes:
  ipfs_staging:
  ipfs_data:
  lasr_data:
