---
version: "3"

dotenv: [".config.env"]

includes:
  fly: .taskfiles/fly/tasks.yaml
  github: .taskfiles/github/tasks.yaml

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  step_1:
    cmds:
      - rm -rf blocks_processed.dat

  step_2:
    cmds:
      - anvil

  step_3:
    cmds:
      - cd ./executable-oracle-eth
      - bun run deploy:local

  step_4:
    cmds:
      - ./target/debug/main

  step_5:
    cmds:
      - cast send --from 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 --unlocked 0x5FbDB2315678afecb367f032d93F642f64180aa3 --value 1000000

  step_6:
    cmds:
