[contract]
name = "EscrowContract"
version = "0.1.0"
language = "Rust"

[contract.ops.deposit]
description = "Handles depositing of fungible tokens into escrow"

[contract.ops.deposit.signature]
depositor = "Address"
redeemer = "Address"
deposit_token_address = "Address"
deposit = "BigInt"
conditions = "Mapping"
maturity = "BigInt"


[contract.ops.deposit.signature.params_mapping]
depositor = { source = "transaction", field = "from" }
redeemer = { source = "transaction", field = "inputs", key = "redeemer" }
deposit_token_address = { source = "transaction", field = "program_id" }
deposit = { source = "transaction", field = "inputs", key = "deposit" }
conditions = { source = "transaction", field = "inputs", key = "conditions" }
maturity = { source = "transaction", field = "inputs", key = "maturity" }


[contract.ops.redeem]
description = "Handles the redemption of token if condition(s) met" 

[contract.ops.redeem.signature]
escrow_address = "Address"
redeemer = "Address"
deposit_token_address = "Address"
deposit_id = "FixedBytes(32)"
conditions = "String"
item_address = "Address"
item = "BigInt"


[contract.ops.redeem.signature.params_mapping]
escrow_address = { source = "transaction", field = "to" }
redeemer = { source = "transaction", field = "from" }
deposit_token_id = { source = "transaction", field = "inputs", key = "deposit_token_id" }
conditions = { source = "read" }
item_address = { source = "transaction", field = "program_id" }
item = { source = "transaction", field = "inputs", key = "item" }

[[contract.ops.redeem.required]]
type = "Read"
details = { items = [["escrow_address", "deposit_token_address", "data"]], contract_blobs = [] }

[contract.ops.revoke]
description = "Allows the depositor to revoke the escrow and reclaim the tokens if conditions are not met by maturity"

[contract.ops.revoke.signature]
escrow_address = "Address"
deposit_id = "FixedBytes(32)"
depositor_address = "Address"
timestamp = "BigInt"
maturity = "BigInt"

[contract.ops.revoke.signature.params_mapping]
escrow_address = { source = "transaction", field = "to" }
deposit_id = { source = "transaction", field = "inputs", key = "deposit_id" }
depositor_address = { source = "transaction", field = "from" }
timestamp = { source = "call" }
maturity = { source = "read" }

[[contract.ops.revoke.required]]
type = "Call"
details = { calling_program = "Address", original_caller = "Address", program_id = "Address", inputs = "" }

[[contract.ops.revoke.required]]
type = "Read"
details = { items = [["escrow_address", "deposit_id", "data"]], contract_blobs = [] }
